### ISSUE TITLE
The last patch version of uint8arrays breaks all Node 12 applications because of BREAKING multibase upgrade

### ISSUE THREAD

**Issue by dlecan** [achingbrain/uint8arrays#15]
Hello,

Do you follow semver?

Multibase >= 4 requires Node 14, so all my applications are broken after a "patch" update of this module.

**Comment by achingbrain** [comment]
A new version of multibase that lowers the node version in the `engines` field has been released, so if you remove your lockfiles/node_modules folder and reinstall you should be ok now.

AFAIK there's no actual node-14+ specific stuff in there, and the `engines` field is just advisory - are you actually seeing breakage or did you open this issue because of the warning npm prints?

**Comment by dlecan** [comment]
> are you actually seeing breakage or did you open this issue because of the warning npm prints?
Yarn builds are blocked by such enforcements.
Anyway, issue is fixed, thank you.
